Improvments
ngulden/niculskin pull request #1
Opened 2018-01-21 18:53 UTC by seehase

Added UV/Solar/ET

2018-01-21 19:47 UTC, seehase commented
There is still a bug if you use other languages than german
because 'extra1_temp_humidity' cannot be translated with a default value 
My fix didn't solve that problem, but if you don't have these extra data, than it works also in other languages ... If I find some more time I'll fix it
You can see the new version on my site under 
https://solar.seehausen.org/weewx/
I integrated weewx into my solar logger project
Kind regards 
Holger

2018-01-21 20:38 UTC, ngulden commented
Hi Holger,

thank you very much for the pull request. I try to give it review the next couple days.

Best regards,
Nico

2018-02-05 19:06 UTC, ngulden commented on skins/niculskin/index.html.tmpl
> +                        #if $day.extraTemp1.has_data
Should this say $day.extra.Temp2.has_data?

2018-02-05 19:13 UTC, ngulden commented on skins/niculskin/index.html.tmpl
> +                        <tr><td>UV</td><td>$current.UV</td></tr>
Please use a reference to the label. The english value is defined in the skin.conf starting at [line 266](https://github.com/ngulden/niculskin/blob/d534d27e9616359fa150a6fc20e1f39ca07fe9b2/skins/niculskin/skin.conf#L266). For example add a new line after line 286 with uv, et and radiation.

This way the template remains translatable and other languages can easily be added to the appropriate language skin subdirectory.

2018-02-05 19:14 UTC, ngulden commented on skins/niculskin/index.html.tmpl
> +                        <tr><td>High UV</td><td>$day.UV.max</td><td>$day.UV.maxtime</td></tr>
The same with the labels here. Add them to the skin.conf file and just refer to them from the template, e.g. `$niculskinLabels.conditions.uv_max`.

2018-02-05 19:16 UTC, ngulden requested changes
The patch looks good so far. Please see the comments and use references for the labels. This keeps the template translatable.

2018-02-10 16:09 UTC, closed without merging