Added also UV maximum to history page
ngulden/niculskin pull request #3
Opened 2018-01-23 19:28 UTC by seehase

2018-02-05 09:43 UTC, seehausen commented
any updates on my pull request?

2018-02-05 19:04 UTC, ngulden commented
I'm sorry, but I didn't have the time yet to take a look.

2018-02-05 19:17 UTC, ngulden commented on skins/niculskin/index.html.tmpl
> +                        #if $day.extraTemp1.has_data
Please see https://github.com/ngulden/niculskin/pull/1#pullrequestreview-94105600

2018-02-05 19:19 UTC, ngulden requested changes
This looks like the same patch as in https://github.com/ngulden/niculskin/pull/1. Please make the changes asked for in that pull request and submit them. Afterwards, you can rebase this pull request on those changes and I'd happily accept them.

2018-02-10 13:48 UTC, seehase commented
Changed everything to use lables and fixed all of your comments

2018-02-13 08:25 UTC, ngulden approved these changes
Thanks for the adjustments. They look good.

2018-02-13 08:25 UTC, ngulden commented
@seehase : Thank you very much for you contribution.

2018-02-13 08:25 UTC, merged